runtime: php
env: flex

runtime_config:
  document_root: public

skip_files:  
  - .env

env_variables:
  APP_LOG: errorlog
  APP_KEY: base64:BEVs/DqwJFIx+WAhNu/AMgbs3uv4rOyg84kgFgMg81M=
  STORAGE_DIR: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  DB_HOST: localhost
  DB_DATABASE: zoho_portal
  DB_USERNAME: root
  DB_PASSWORD: 118097
  DB_SOCKET: "/cloudsql/zoho-portal-159018:us-central1:zoho-portal"

beta_settings:
    cloud_sql_instances: "zoho-portal-159018:us-central1:zoho-portal"